Add responsive margin collapse
canonical/vanilla-framework pull request #3991
Opened 2021-09-21 15:25 UTC by petesfrench

## Done

Adds responsive margin collaspe

Fixes https://github.com/canonical-web-and-design/vanilla-framework/issues/3020

## QA

- Open [demo](https://vanilla-framework-3991.demos.haus/docs/examples/utilities/margin-collapse-responsive)
- Check margins collapse appropriately
- Check docs are working and clear

### Check if PR is ready for release

If this PR contains Vanilla SCSS code changes, it should contain the following changes to make sure it's ready for the release:

- [ ] PR should have one of the following labels to automatically categorise it in release notes:
  - `Feature 🎁`, `Breaking Change 💣`, `Bug 🐛`, `Documentation 📝`, `Maintenance 🔨`.
- [ ] Vanilla version in `package.json` should be updated relative to the [most recent release](https://github.com/canonical-web-and-design/vanilla-framework/releases/latest), following semver convention:
  - if CSS class names are not changed it can be bugfix relesase (x.x.**X**)
  - if CSS class names are changed/added/removed it should be minor version (x.**X**.0)
  - see the [wiki for more details](https://github.com/canonical-web-and-design/vanilla-framework/wiki/Release-process#pre-release-tasks)
- [ ] Any changes to component class names (new patterns, variants, removed or added features) should be listed on the [what's new page](https://github.com/canonical-web-and-design/vanilla-framework/blob/master/templates/docs/whats-new.md).
- [ ] Documentation side navigation should be updated with the relevant labels.

## Screenshots

[if relevant, include a screenshot or screen capture]

2021-09-21 15:25 UTC, webteam-app commented
Demo starting at https://vanilla-framework-3991.demos.haus

2021-09-22 10:54 UTC, bartaz requested changes
We just talked with Ant about it a bit, and we thought it would be better to just do it for bottom utilities for now only. That's the only use case we have, so lets fix that and not introduce class names that are likely not going to be used.

It's easier to add them later than remove.

2021-09-22 10:54 UTC, bartaz commented on templates/docs/utilities/margin-collapse.md
> +<hr>
We usually only use those under the main title, so remove it please

2021-09-22 10:54 UTC, bartaz commented on templates/docs/utilities/margin-collapse.md
> +<div class="embedded-example"><a href="/docs/examples/utilities/margin-collapse-responsive/" class="js-example">
I'm wondering about usefulness of this example as embedded in docs. It's quite long, size of the screen can't be changed in embedded example, etc.

As we discussed reducing it to bottom only, maybe lets to it first and see if the example will still be too much.

2021-09-23 11:03 UTC, sowasred2012 commented
Added `Don't merge` label, this needs more thinking about.

@bartaz had the good idea to update the example to demonstrate the use case we already have for this: two buttons that we want to maintain a margin between on small screens only (when the buttons become stacked).

In line with what we do for the [`u-hide` utility](https://github.com/canonical-web-and-design/vanilla-framework/blob/master/scss/_utilities_hide.scss#L23), the utilities we've introduced do the following:

| class                      | media query                                                       |
| -------------------------- | ----------------------------------------------------------------- |
| u-no-margin--bottom-small  | max-width: $breakpoint-medium - 1                                 |
| u-no-margin--bottom-medium | min-width: $breapoint-medium and max-width: $breakpoint-large - 1 |
| u-no-margin--bottom-large  | min-width: $breakpoint-large                                      |

The problem is that buttons are only actually full width _up to_ `$breakpoint-small`, after that they're `width: auto;`, so if I were to follow my instinct and add a `button.u-no-margin--medium.u-no-margin--bottom-large` element to meet the use case, what I'd end up with is buttons that look as expected on every breakpoint except where `$breakpoint-x-small` ends and `$breakpoint-medium` begins, like so:

![Peek 2021-09-23 11-43](https://user-images.githubusercontent.com/2376968/134494403-28f18090-4d17-4d5a-8f38-dcb60b73dee6.gif)

I think it makes sense to stick to the media query/naming convention used in the `u-hide` utility, so I didn't want to alter the media queries behind these new utilities; changing the media query for `u-no-margin--bottom-small` to have a min-width seemed like a bad idea that could cause confusion when used with other responsive utility classes.

I then thought about adding another utility, `u-no-margin--bottom-x-small` and updating `u-no-margin--bottom-small` anyway, so we'd have a set like this:

| class                      | media query                                                       |
| -------------------------- | ----------------------------------------------------------------- |
| u-no-margin--bottom-x-small  | max-width: $breakpoint-x-small - 1                                 |
| u-no-margin--bottom-small  | min-width: $breakpoint-x-small and max-width: $breakpoint-medium - 1                                 |
| u-no-margin--bottom-medium | min-width: $breapoint-medium and max-width: $breakpoint-large - 1 |
| u-no-margin--bottom-large  | min-width: $breakpoint-large                                      |

But with this, coming back to the use case, to achieve it we'd need a `button.u-no-margin--bottom-small.u-no-margin--bottom--medium.u-no-margin--bottom-large`, which looks mad.

On top of that, it's pretty likely `u-no-margin--bottom-x-small` would never get used, so it's main reason for existing is to hopefully make it more obvious that `u-no-margin--bottom-small` has a lower boundary.

@bartaz @anthonydillon would love to get your thoughts on this. I'm wondering whether this actually needs to be specific to the button pattern, maybe a `is-stacked--small` utility that handles the margins between them (I'm not married to that classname though).

2021-09-23 11:44 UTC, bartaz commented
It seems that the issue we are having with button margins is caused by the fact that on x-small screens we are making buttons full width by default.

Maybe the solution is getting rid if this. If buttons behave normally on all screen sizes, we won't have issues with margins.
We can always make a 'full width mobile' variant button as an opt-in rather than default.

2021-10-06 14:40 UTC, lyubomir-popov commented
I like the suggestion of doing full-width buttons with a bespoke class, which would solve the problems  blocking this  issue. @anthonydillon does that sound ok to you? We could include it in the 3.0 upgrade guide.

2021-10-12 12:00 UTC, closed without merging