Fix nested list counter
canonical/vanilla-framework pull request #5011
Opened 2024-02-28 13:30 UTC by codeEmpress1

## Done
- Fix nested list counter
[List of work items including drive-bys]

Fixes [list issues/bugs if needed]
https://github.com/canonical/vanilla-framework/issues/4998

## QA

- Open [demo](insert-demo-url)
- [Add QA steps]
- Review updated documentation:
  - [List any updated documentation for review]

### Check if PR is ready for release

If this PR contains Vanilla SCSS code changes, it should contain the following changes to make sure it's ready for the release:

- [ ] PR should have one of the following labels to automatically categorise it in release notes:
  - `Feature 🎁`, `Breaking Change 💣`, `Bug 🐛`, `Documentation 📝`, `Maintenance 🔨`.
- [ ] Vanilla version in `package.json` should be updated relative to the [most recent release](https://github.com/canonical/vanilla-framework/releases/latest), following semver convention:
  - if CSS class names are not changed it can be bugfix relesase (x.x.**X**)
  - if CSS class names are changed/added/removed it should be minor version (x.**X**.0)
  - see the [wiki for more details](https://github.com/canonical/vanilla-framework/wiki/Release-process#pre-release-tasks)
- [ ] Any changes to component class names (new patterns, variants, removed or added features) should be listed on the [what's new page](https://github.com/canonical/vanilla-framework/blob/main/releases.yml).

## Screenshots
### Before
![image](https://github.com/canonical/vanilla-framework/assets/47438585/e4e3f7a2-c3f8-415a-8433-8025595dac00)

### After
![Screenshot from 2024-03-01 11-50-32](https://github.com/canonical/vanilla-framework/assets/47438585/21c354cf-503b-4f20-af60-596c859f56a2)

[if relevant, include a screenshot or screen capture]

2024-02-28 13:30 UTC, webteam-app commented
Demo starting at https://vanilla-framework-5011.demos.haus

2024-02-29 10:44 UTC, bartaz commented on scss/_patterns_lists.scss
> +      counter-reset: li;
I think the changes you made here are in good direction, but are not necessary in this form.

Overall, I believe the bug comes from the fact that we use 2 different counters in different lists: we use `li` counter and `list-item` counter. The stepped list uses one of them (`li`) and the divided list uses the other (`list-item`).

I believe the difference is not necessary. We can use the same counter in both (so they correctly reset and increment). 

So I think the fix for the issue would be to change any references to counters to use the same one (either `li` or `list-item` - doesn't matter, just the same everywhere).
So any `counter-reset`, `counter-increment` or value of `counter(…)` should use the same (`list-item` for example).

2024-03-01 10:38 UTC, bartaz commented on templates/docs/examples/patterns/lists/list-nested-stepped-detailed.html
> +{% block title %}Lists / Nested Stepped Detailed Ordered List{% endblock %}
```suggestion
{% block title %}Lists / Ordered list nested in stepped list{% endblock %}
```

2024-03-01 10:47 UTC, bartaz approved these changes
LTGM, thanks a lot!

2024-03-01 10:56 UTC, bartaz requested changes
There is some issue with standard stepped list now, that it increases by 2 on each level:
https://vanilla-framework-5011.demos.haus/docs/patterns/lists#vertical-stepped

<img width="771" alt="image" src="https://github.com/canonical/vanilla-framework/assets/83575/0043056d-2bb7-4f7f-be7f-951fac9e6f94">

I haven't checked in detail yet, but maybe `counter-increment` happens twice or something like that.

2024-03-01 10:59 UTC, codeEmpress1 commented
> There is some issue with standard stepped list now, that it increases by 2 on each level: https://vanilla-framework-5011.demos.haus/docs/patterns/lists#vertical-stepped
> 
> <img alt="image" width="771" src="https://private-user-images.githubusercontent.com/83575/309236596-0043056d-2bb7-4f7f-be7f-951fac9e6f94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyOTEwMDgsIm5iZiI6MTcwOTI5MDcwOCwicGF0aCI6Ii84MzU3NS8zMDkyMzY1OTYtMDA0MzA1NmQtMmJiNy00ZjdmLWJlN2YtOTUxZmFjOWU2Zjk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDEwNTgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkYWMyMmQxYmQ5Mzg2MGNjYTE4Y2UzM2ViNWE3MmRmN2QwYWMyMWNmODI2NjdlYjI0ODQ4MThiNGU1MjBjOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jSzUisdCe7UF7C0NmXHI65Eq1iVqmOehChJxpHWAfeM">
> I haven't checked in detail yet, but maybe `counter-increment` happens twice or something like that.

Ohh, Yea. It happens twice for this, I'll look at it

2024-03-05 16:12 UTC, bartaz commented
@codeEmpress1 It seems the issue was that we've been using default browser `list-item` counter, which is also increased natively by the browser. So the counter was increased both by `li` element, and by `__title` class.

I moved counter increase to `li` element, so this only happens there and not in the title as well. This seems to help.

Please review/QA if all looks good from your side. Thanks.

2024-03-05 16:45 UTC, codeEmpress1 commented
LGTM!

2024-03-06 08:58 UTC, merged