Add form legend required symbol
canonical/vanilla-framework pull request #5214
Opened 2024-07-11 03:41 UTC by britneywwc

## Done

- Add `is-required` class to fieldset legend

Fixes [list issues/bugs if needed]

## QA

- Open [demo](insert-demo-url) /docs/examples/patterns/forms/forms-required?theme=light
- See that the asterisk shows for fieldset is-required legend

### Check if PR is ready for release

If this PR contains Vanilla SCSS code changes, it should contain the following changes to make sure it's ready for the release:

- [ ] PR should have one of the following labels to automatically categorise it in release notes:
  - `Feature 🎁`, `Breaking Change 💣`, `Bug 🐛`, `Documentation 📝`, `Maintenance 🔨`.
- [ ] Vanilla version in `package.json` should be updated relative to the [most recent release](https://github.com/canonical/vanilla-framework/releases/latest), following semver convention:
  - if CSS class names are not changed it can be bugfix relesase (x.x.**X**)
  - if CSS class names are changed/added/removed it should be minor version (x.**X**.0)
  - see the [wiki for more details](https://github.com/canonical/vanilla-framework/wiki/Release-process#pre-release-tasks)
- [ ] Any changes to component class names (new patterns, variants, removed or added features) should be listed on the [what's new page](https://github.com/canonical/vanilla-framework/blob/main/releases.yml).

## Screenshots

[if relevant, include a screenshot or screen capture]

2024-07-11 03:41 UTC, webteam-app commented
### [<img src='https://assets.ubuntu.com/v1/6baef514-ubuntu-circle-of-friends-large.svg' height=32 width=32> Demo</img>](https://vanilla-framework-5214.demos.haus)
### [<img src='https://assets.ubuntu.com/v1/e512b0e2-jenkins.svg' height=32 width=32> Jenkins </img>](https://jenkins.canonical.com/webteam/job/start-demo/4523)
### [<img src='https://assets.ubuntu.com/v1/7144ec6d-logo-jaas-icon.svg' height=32 width=32> demos.haus </img>](https://demos.haus)

2024-07-11 08:03 UTC, bartaz commented
Thanks @britneywwc, could you share some context to it, where do we show required on fieldset level instead of input level?

2024-07-11 08:13 UTC, britneywwc commented
Hi @bartaz. Yeah sure, when checkbox/radio inputs are grouped under a fieldset and we wish to set the legend for that fieldset group to show that it's required. We set required on the input level as well but the intention behind this is to show the required label (*) on the corresponding legend.

Example use case here: https://github.com/canonical/ubuntu.com/blob/56e02eb43914c928fc20e553f75eb70ae56e4d74/templates/kernel/real-time/contact-us.html#L312

Please let me know it makes sense to add it to the legend field, it's ongoing work so I figured this could be upstreamed if useful.

2024-07-11 08:46 UTC, bartaz commented
In such case I'd suggest making an example that reflects this use case (have a group of checkboxes inside the fieldset, rather than text input).

2024-07-11 08:48 UTC, bartaz commented on scss/_base_reset.scss
> +    &.is-required::before {
The top of the file says `// DO NOT edit this file except to upgrade Normalize in it's entirety` :)

This is a CSS that comes form external reset library. It's meant to provide a clean state. No class names or specific styling should be defined here.

Please move the legend styling to `_base_form.scss`.

2024-07-22 12:50 UTC, bartaz commented
There seem to be some linting/prettier issues that fail the tests. You can run `dotrun test` locally to see them as well.

For the linter failing that we don't allow element selectors, just disable linting for that (we are doing that for all base styles, because we expect them to be on elements).

2024-08-13 15:03 UTC, jmuzina requested changes
Added a note about adding this to combined forms example to ensure this gets tested by Percy.

Also, I think this should set `package.json` package version to `4.15.1` as `4.15.0` has already been released and no PR has updated `main` to `4.15.1` yet.

2024-08-13 15:03 UTC, jmuzina commented on templates/docs/examples/patterns/forms/fieldset-required.html
Please add this new example to `templates/docs/examples/patterns/forms/combined.html` - you can just add a new `<section>` that includes this example. This will make sure it shows up in our Percy tests

2024-08-13 15:11 UTC, jmuzina requested changes

2024-08-13 15:11 UTC, jmuzina commented on templates/docs/examples/patterns/forms/fieldset-required.html
> +    <legend class="is-required" for="list-input-1">Required input</legend>
I don't think the `for` attribute is supported for the `<legend>` element ([MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/legend))

2024-08-13 15:11 UTC, jmuzina commented on templates/docs/examples/patterns/forms/fieldset-required.html
> +      <input type="radio" class="p-radio__input" name="radioPattern" aria-labelledby="radioExample1">
These three `span`s all have the same `id`, and the `inputs` have the same `aria-labelledby` - can we adjust so the `id` fields are unique and `aria-labelledby` references the ID of the adjacent label?

2024-08-14 02:53 UTC, britneywwc commented
Thanks for all the suggestions, I've addressed them in the recent pushes. Please have another look!

2024-08-14 03:01 UTC, jmuzina commented
Thanks @britneywwc ! Another thing - can we get an entry in releases.yml announcing the new class variant?

2024-08-14 17:47 UTC, jmuzina commented on scss/_base_forms.scss
> +      content: '* ' !important;
@pastelcyborg  This makes this component inconsistent with `label.is-required` from `_base_forms.scss` - should we also adjust the spacing to use `margin-right` there? ([src](https://github.com/canonical/vanilla-framework/blob/1525b35b87e14f5f85cfbc5d4eb892f9f8e38bff/scss/_base_forms.scss#L111-L114))

I'm inclined to say yes.

2024-08-15 13:16 UTC, jmuzina approved these changes

2024-08-15 13:17 UTC, merged