Update remaining legacy components to use new theme colours.
canonical/vanilla-framework pull request #5377
Opened 2024-10-10 11:43 UTC by bartaz

## Done

Updates couple remaining small components (badge, deprecated image options, deprecated full-width layout) to use new theming variables.

Fixes https://warthogs.atlassian.net/browse/WD-11862
Fixes https://warthogs.atlassian.net/browse/WD-11870
Fixes https://warthogs.atlassian.net/browse/WD-11884

## QA

- Open [demo](insert-demo-url)
- [Add QA steps]
- Review updated documentation:
  - [List any updated documentation for review]

### Check if PR is ready for release

If this PR contains Vanilla SCSS code changes, it should contain the following changes to make sure it's ready for the release:

- [ ] PR should have one of the following labels to automatically categorise it in release notes:
  - `Feature 🎁`, `Breaking Change 💣`, `Bug 🐛`, `Documentation 📝`, `Maintenance 🔨`.
- [ ] Vanilla version in `package.json` should be updated relative to the [most recent release](https://github.com/canonical/vanilla-framework/releases/latest), following semver convention:
  - if CSS class names are not changed it can be bugfix release (x.x.**X**)
  - if CSS class names are changed/added/removed it should be minor version (x.**X**.0)
  - see the [wiki for more details](https://github.com/canonical/vanilla-framework/wiki/Release-process#pre-release-tasks)
- [ ] Any changes to component class names (new patterns, variants, removed or added features) should be listed on the [what's new page](https://github.com/canonical/vanilla-framework/blob/main/releases.yml).

## Screenshots

[if relevant, include a screenshot or screen capture]

2024-10-10 11:43 UTC, webteam-app commented
### [<img src='https://assets.ubuntu.com/v1/6baef514-ubuntu-circle-of-friends-large.svg' height=32 width=32> Demo</img>](https://vanilla-framework-5377.demos.haus)
### [<img src='https://assets.ubuntu.com/v1/e512b0e2-jenkins.svg' height=32 width=32> Jenkins </img>](https://jenkins.canonical.com/webteam/job/start-demo/19324)
### [<img src='https://assets.ubuntu.com/v1/7144ec6d-logo-jaas-icon.svg' height=32 width=32> demos.haus </img>](https://demos.haus)

2024-10-10 13:16 UTC, bartaz commented
Badges theming discussed with Lyubo on standup. We want to use the "inverse" colours there.

2024-10-11 20:03 UTC, jmuzina requested changes
Needs a `package.json` version bump to `4.17.2` I suppose, since this makes some small changes to our built CSS and `4.17.1` has already been released. Otherwise this is good!

2024-10-17 04:12 UTC, bartaz commented
> Needs a `package.json` version bump to `4.17.2` I suppose, since this makes some small changes to our built CSS and `4.17.1` has already been released. Otherwise this is good!

Now we have 4.18 in main branch, so it's OK to skip version bump.

2024-10-17 04:18 UTC, jmuzina approved these changes

2024-10-17 04:19 UTC, merged